project:
  type: website

website:
  title: "Les Forces dans ma Classe"
  page-footer: "2022/2023 - Un projet de Nicolas Bressoud - chEERSlab" 
  favicon: "img/fav-cheers.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: activites-pedagogiques.qmd
        text: Activités pédagogiques
      - href: mesures.qmd
        text: Mesures et récolte de données
      - href: about.qmd
        text: A propos

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-newwindow: true


margin-header: |
  ![](img/logo-cheers.png)

