---
title: "Activités pédagogiques"
toc-title: "Sur cette page"
from: markdown+emoji
---

Le design de la recherche implique : 

- 6 classes d'enfants de 8 à 12 ans (groupe expérimental)
- 4 classes d'enfants de 8 à 12 ans (groupe contrôle)

## Matériel à disposition

Le matériel qui peut être convoqué pour nourrir les activités ci-dessous s'appelle *A chacun ses force (et forts ensemble)*. Développé notammen par Anaïs Blot, Laetitia Mascolo, Laure Coutaz Bressoud et Nicolas Bressoud, il cadre la progression pédagogique attendue.

### Téléchargement en accès limité

- [Poster, plateau de jeu, cartes d'activité, cartes des forces, livret de l'élève, guide de l'enseignant·e.](https://drive.switch.ch/index.php/s/DkpLRa5PY1PPqSZ)


## Activités du groupe expérimental

Les enseignantes du groupe expérimental sont parties prenantes du projet. Elles ont suivi une formation continue, accepté de participer au projet, et sont au contact des élèves qui bénéficient du programme.

### Semaine 1 / 9 - 24 au 28 octobre 2022

<details>
  <summary>Cliquez pour voir les détails de la semaine 1</summary>
#### Intention générale de la semaine :

**Découvrir les 24 forces pour percevoir la diversité de nos ressources**

#### Message-clé de la semaine : 

*"On a toutes et tous 24 forces plus ou moins intenses. Comme on est tous différents, chacun a son propre mélange d'intensité de forces. Ce qui est important, c'est de savoir les repérer pour les utiliser."*

#### Moyens pour y parvenir :

- Présenter le vocabulaire des 24 forces
- Donner des exemples de personnes dont les actions permettent de repérer des forces (Superman est modeste, etc)
- Donner un exemple observé par l'enseignante en classe en l'associant à un moment ("j'ai repéré de la prudence dans notre classe au moment où vous avez commencé la fiche, ...")
- Petit-à-petit donner les actions en lien avec les forces ("j'ai repéré de la prudence dans notre classe au moment où vous avez commencé la fiche : des élèves ont retourné la feuille pour vérifier si quelque chose devait être fait au verso.")

#### Exemples d'activités concrètes tirées du matériel : 

- Une personne est désignée pour venir devant la classe et penser à une force. Le reste de la classe va devoir deviner de quelle force il s’agit en posant des questions.
- Recevoir une situation dans laquelle une force est utilisée. En groupe, lire la situation et identifier les forces qui sont présentes. 

#### Temps total à consacrer :

environ 60 min en 1 ou plusieurs moments

#### Conseils : 

- Montrez aux élèves que vous savez repérer des forces en classe.
- Soyez toujours en lien avec des actions.
- Insistez sur le fait que chaque élève a son "cocktail" des forces et qu'il apporte du positif à la classe.

</details>

### Semaine 2 / 9 - 31 au 4 novembre 2022

<details>
  <summary>Cliquez pour voir les détails de la semaine 2</summary>
#### Intention générale de la semaine :

**Découvrir les 24 forces pour percevoir la diversité de nos ressources**

#### Message-clé de la semaine : 

*"Dans notre classe, il y a plein de forces qui émergent et nous aident à être bien ensemble et bien travailler."*

#### Moyens pour y parvenir :

- Donner un exemple observé par l'enseignante en classe en suscitant peu à peu la réflexion chez les élèves ("j'ai repéré de la prudence pendant la pause. Savez-vous ce que j'ai vu ?")
- Utiliser les FAB de **Fabrice Dini** : (1) l'action - (2) la force - (3) le bienfait ("quand tu as (1) laissé parler ton camarade, tu as fait preuve de (2) maîtrise de soi et ça a (3) amené du calme en classe.")
- Observer des situations "fictives" ou "passées" de vie de classe pour identifier les forces permettant de soutenir les solutions (résolution de conflits, aide au travail, ...)

#### Exemples d'activités concrètes tirées du matériel : 

- A partir des définitions des forces, retrouver l'intitulé et vice versa (mémory ou mots à relier ou mots-croisés)
- S'entrainer à définir les forces
- Lire une des histoires qui permet de comprendre le rôle d'une force de votre choix

#### Temps total à consacrer :

environ 60 min en 1 ou plusieurs moments

#### Conseils : 

- Prenez encore une grande place dans cette semaine pour être exemplaire et faciliter le modelage chez les élèves.
- En tant qu'enseignante, mettez-vous des rappels pour orienter l'attention des élèves sur des moments de vie de la classe où des forces peuvent être repérées.
- Cadrez bien l'idée que chaque enfant a les 24 forces, mais de manière plus ou moins optimale, selon les personnes. C'est cette diversité qui est intéressante.

</details>

### Semaine 3 / 9 - 7 au 11 novembre 2022

<details>
  <summary>Cliquez pour voir les détails de la semaine 3</summary>
#### Intention générale de la semaine :

**Observer les forces des camarades de classe**

#### Message-clé de la semaine : 

*"Si j'observe de la bonne manière, alors je peux repérer des forces dans la classe. Quand j'observe un·e camarade, je peux deviner une force derrière certaines de ses actions"*

#### Moyens pour y parvenir :

- L'enseignante peut partir de l'exemple d'une personne connue pour que les élèves identifient (1) des actions remarquables qui (2) révèlent des forces
- L'enseignante rappelle qu'on a toutes et tous des forces ; l'enjeu est de savoir les repérer
- Quand on fait une action qui apporte du bon, on utilise une force.
- Se donner régulièrement des petits défis pour trouver la force derrière une action observée.

#### Exemples d'activités concrètes tirées du matériel : 

- jouer au détective des forces : en collectif, on se concentre sur chaque enfant, sous la guidance (préparée) de l'enseignante ; le but est que, à partir d'une action que donne l'enseignante, on trouve une force sous-jacente ("Louis a attendu que tout le monde soit prêt avant de prendre la parole. Il a fait preuve de maîtrise de soi.")
- jouer au détective des forces : se transformer en enquêteur ou enquêtrice pendant quelques jours. Le défi est, à partir d'une "cible" donnée par l'enseignante, de repérer une action liée à une force. L'enseignante s'assurer de trouver les bonnes cibles et soutient la réussite du projet auprès de chaque élève. Ensuite, on peut communiquer ce qu'on a observé pour que chaque élève reçoive un feedback sur une de ses actions et une force sous-jacente.

#### Temps total à consacrer :

environ 60 min en 1 ou plusieurs moments

#### Conseils : 

- Vous devez coacher vos élèves pour qu'ils apprennent à focaliser leur attention sur les ressources chez les autres ; ils ont besoin de votre aide dans cet apprentissage.
- Ici, on commence à avoir des enjeux relationnels : veillez à ce que personne ne soit laissé de côté.

</details>

### Semaine 4 / 9 - 14 au 18 novembre 2022

<details>
  <summary>Cliquez pour voir les détails de la semaine 4</summary>
#### Intention générale de la semaine :

**Observer les forces des camarades de classe**

#### Message-clé de la semaine : 

*"Avec de l'entrainement, on voit que c'est de plus en plus facile d'observer des forces chez tous les camarades de la classe. On observe que certains ont des forces qui leur vont bien (les forces de signature)."*

#### Moyens pour y parvenir :

- S'assurer que les 24 forces sont connues (une familiarisation a été effectuée durant les 3 premières semaines)
- Continuer à utiliser les FAB de Fabrice Dini : (1) l’action - (2) la force - (3) le bienfait (“quand tu as (1) attendu Julie, tu as fait preuve de (2) gentillesse et ça a (3) donné un chouette exemple de camaraderie aux copains.”)
- **(nouveau)** Face à un problème ou une difficulté, on commence à se demander quel·le camarade de classe peut nous apporter une aide en fonction de ses forces ("Je pense que Pierre peut me conseiller pour me calmer au vestiaire car il faut souvent preuve de maîtrise de soi").
- **(nouveau)** Faire un tour de classe où chaque élève est nommé avec ses **forces de signature**, c'est-à-dire les forces qui sont bien mises en avant chez lui ou elle ; attention, on s'assure que (1) tous les enfants soient concernés par l'activité et que (2) on nomme le même nombre de forces à chacun·e (par exemple 2).

#### Exemples d'activités concrètes tirées du matériel : 

- Choisir un·e camarade qu'on ne connait pas très bien et identifier ses forces dans diverses situations ; se faire aider par l'enseignante pour ne pas faire chou blanc.
- Lire le conte et essayer d'identifier les forces des personnages principaux.
- Décrire une situation où son voisin de banc a mis une force en action.

#### Temps total à consacrer :

environ 60 min en 1 ou plusieurs moments

#### Conseils : 

- Soyez vigilantes dans l'entretien du vocabulaire des forces en le convoquant le plus naturellement possible.
- Veillez à ces que les forces convoquées soient toujours en lien avec des actions concrètes ; on ne veut pas glisser vers des "qualités statiques" ; les forces sont toujours "en action".
- Assurez-vous qu'aucun enfant ne soit laissé de côté dans l'exercice ; c'est ainsi que le climat de classe commence à être influencé favorablement.
- Admettez, avec les élèves, qu'on a aussi des caractéristiques intéressantes qui semblent coller à notre identité (par exemple, "quand on pense au sens du pardon, on pense à Camille qui montre souvent cette force.")

</details>

### Semaine 5 / 9 - 21 au 25 novembre 2022

<details>
  <summary>Cliquez pour voir les détails de la semaine 5</summary>
#### Intention générale de la semaine :

**Identifier ses propres forces**

#### Message-clé de la semaine : 

*"Les forces de signature sont notre fil rouge de la semaine. Chaque élève a reçu un feedback des autres sur une ou plusieurs de ses forces. Maintenant, on commence enfin à s'observer soi-même. On se rend peu à peu compte soi-même que, quand on fait quelque chose (1) bien, (2) avec plaisir et (3) souvent, il y a une force derrière.*

#### Moyens pour y parvenir :

- S'assurer que chaque élève a le même nombre de forces reconnues par le groupe-classe (par exemple, dans une classe, on reconnaît deux forces à chaque enfant, et personne n'a aucune force reconnue)
- Demander aux élèves d'évaluer s'ils se reconnaissent dans les forces attribuées par le groupe (c'est ok si un enfant ne se retrouve pas)
- Challenger les élèves petit-à-petit pour documenter quand et comment ils utilisent leurs forces de signatures (cela peut être les forces reconnues par le groupe ou bien d'autres forces) ; comme toujours, ce qui compte est de lier à une action.

#### Exemples d'activités concrètes tirées du matériel : 

- Durant une semaine, créer le carnet de bord de ses propres forces de caractère. Noter toutes les situations où une force a été utilisée. Faire un bilan en fin de semaine.
- Identifier les 4 forces qui me représentent le plus et les dessiner sur mon blason. Ecrire le nom de mes forces sous les dessins. Ou écrire mes 5 forces dans les pétales de la fleur, coller ma photo au centre.

#### Temps total à consacrer :

environ 60 min en 1 ou plusieurs moments

#### Conseils : 

- Soyez patientes pour permettre aux élève de *ne pas savoir* pendant un temps ; montrez-leur votre confiance dans le temps qu'ils consacrent à s'autoévaluer et le fait qu'ils vont petit-à-petit réussir à voir leurs forces puisque tout le monde a les 24 forces de manière plus ou moins intense (comme un jardin de 24 fleurs où chaque fleur pousse à son rythme) 
- Challengez vos élèves (sur la semaine, vous pourriez vous donner une mission de challenger 4-5 enfants par jour, par exemple) en leur disant, par exemple, "ah, je crois que je vois une force derrière ce que tu fais juste là. Et toi ?"
- Cette phase de prise de conscience de ses propres forces doit être appréhendée avec bienveillance ; montrez votre optimisme :smiley:

</details>

### Semaine 6 / 9 - 28 au 2 décembre 2022

<details>
  <summary>Cliquez pour voir les détails de la semaine 6</summary>
#### Intention générale de la semaine :

**Identifier ses propres forces**

#### Message-clé de la semaine : 

*"Oser communiquer autour de ses propres forces personnelles (forces de signature)."*

#### Moyens pour y parvenir :

- Favoriser avec tact l'expression des enfants (ils sont amenés à se lancer dans le fait *d'oser* parler de leurs forces aux autres)
- Donner des occasions de mémoriser / réactiver des situations où l'enfant à fait (1) bien, (2) avec plaisir et (3) haute énergie quelque chose (par exemple, attendre les copains, ranger son sac, sourire à la directrice, raconter une histoire) pour y greffer les forces. On pourra dire : "souviens-toi quand tu as fait [...action...], il y avait des forces derrière. Tu sais les nommer ?"

#### Exemples d'activités concrètes tirées du matériel : 

- Choisir une force qui me correspond et la présenter sous forme de poster (mots-clé, dessins, flèches, titres...). Venir l’expliquer au reste de la classe ou en groupe.
- Dessiner une situation dans laquelle on s’est senti fier·ère. Identifier ensuite les forces dont on a fait preuve pour pouvoir atteindre quelque chose de bien. Présenter le dessin et l’expliquer au reste de la classe ou en groupe.

#### Temps total à consacrer :

environ 60 min en 1 ou plusieurs moments

#### Conseils : 

- Il est important que les enfants aient une validation des pairs et adultes lorsqu'ils parlent de leurs propres forces. Garantissez ces moments.
- Cela vaut la peine de garder de belles traces de ces moments (joli dessin, par exemple).

</details>

### Semaine 7 / 9 - 5 au 9 décembre 2022

<details>
  <summary>Cliquez pour voir les détails de la semaine 7</summary>
#### Intention générale de la semaine :

**Utiliser les forces du groupe**

#### Message-clé de la semaine : 

*"Voilà ! On est prêts pour le top du top : Faire vivre les forces dans la classe et progresser, en tant que groupe, grâce aux forces de chacun !"*

#### Moyens pour y parvenir :

- Les élèves doivent connaitres les forces les uns des autres. N'hésitez pas à entrainer cela de manière ludique. Ca vient très très vite !
- Commencez à dire à impliquer des élèves en fonction de leurs forces - vous devez aussi les connaitre ou avoir une petite prise de notes sous les yeux - pour coacher la classe selon les défis qui nécessitent des forces spécifiques.

#### Exemples d'activités concrètes tirées du matériel : 

- Recevoir des situations ou un·e élève a un problème. Interpréter la situation en créant une petite saynète. Intervenir avec des forces afin de proposer des solutions aux différents problèmes rencontrés.
- Réfléchir à comment utiliser les forces. Choisir une force que l’on possède et répondre aux questions suivantes par écrit:

    - En quoi ma force pourrait être utile en classe?
    - Que pourrais-je faire concrètement?
    - Comment l’utiliser?
    - Garder cette réflexion et la compléter si de nouvelles idées arrivent.

#### Temps total à consacrer :

environ 60 min en 1 ou plusieurs moments

#### Conseils : 

- Maintenant, on fait circuler les informations pour que les forces soient des moyens de bien vivre ensemble ; en mode "résolution de problèmes", on n'hésite pas à dire "de quelles forces a-t-on besoin pour faire cette exercice de maths ? Et qui peut nous aider dans la classe ?"

</details>

### Semaine 8 / 9 - 12 au 16 décembre 2022

<details>
  <summary>Cliquez pour voir les détails de la semaine 8</summary>
#### Intention générale de la semaine :

**Utiliser les forces du groupe**

#### Message-clé de la semaine : 

*"Message."*

#### Moyens pour y parvenir :

- ...
- ...

#### Exemples d'activités concrètes tirées du matériel : 

- ...
- ...

#### Temps total à consacrer :

environ 60 min en 1 ou plusieurs moments

#### Conseils : 

- ...
- ...

</details>

### Semaine 9 / 9 - 19 au 23 décembre 2022

<details>
  <summary>Cliquez pour voir les détails de la semaine 9</summary>
#### Intention générale de la semaine :

**Célébrer les forces du groupe**

#### Message-clé de la semaine : 

*"Notre classe ne serait pas comme elle est sans les forces que chaque enfant apporte. Et ça, ça se fête."*

#### Moyens pour y parvenir :

- ...
- ...

#### Exemples d'activités concrètes tirées du matériel : 

- ...
- ...

#### Temps total à consacrer :

environ 60 min en 1 ou plusieurs moments

#### Conseils : 

- ...
- ...

</details>
