---
title: "Les Forces dans ma Classe"
toc-title: "Sur cette page"
---

Bienvenue sur le site d'information et de partage du projet de recherche "les forces dans ma classe".

Ce mini-site reçoit et partage les informations propices à orienter l'expérimentation.

## Contexte du projet de recherche

Ce projet s'inscrit dans le thème du développement du fonctionnement optimal et du bien-être des élèves en classes hétérogènes.

Avec les lunettes de la pédagogie spécialisée et celles de la psychologie positive, nous cherchons à observer comment des activités qui visent à identifier, utiliser, cultiver les *forces de caractère* des élèves favorise le développement de relations positives dans la classe et un *rapport à soi* orienté "ressources".

## Intentions (question de recherche)

Dans ce présent projet, nous cherchons plus précisément à observer comment un programme de développement d'une culture des forces influence les élèves de 8 à 12 ans en contextes hétérogènes dans : 

- leur utilisation des forces
- leur relations interpersonnelles dans la classe hétérogène
- leur relation à eux-mêmes.

## Partenaires et échantillon

Ce projet est mené avec des partenaires individuels en Suisse (Valais, Vaud, Fribourg) et en France.

Dans le cadre de l'expérimentation, les partenaires principaux sont : Cécile Gay-des-Combes, Laure Varone, Aferdita Dervodeli, *[à venir]*. Les enseignantes partenaires se basent sur la ligne pédagogique prévue dans la recherche et l'adaptent à leur pédagogie.

## Aspects éthiques

Ce projet est cadré par la décision d'une commission d'éthique universitaire (décision, institution et date de décision à venir).

## Durée du projet

Le projet global commence en août 2022 et se termine en décembre 2022. La phase d'expérimentation commence en octobre 2022 et se termine en décembre 2022 (9 semaines).

## Personne de contact

Nicolas Bressoud, membre du chEERS lab de l'UNIFR
