---
title: "Mesures et récolte des données"
toc-title: "Sur cette page"
---

## Encadrement de la récolte de données

### Consentements 

Les consentement de l'enfant, d'un·e représentant·e légal·e et de l'enseignant·e sont formellement récoltés. Pour ce faire : 

- une formule de consentement est présentée aux familles

- le consentement des enseignantes est obtenu lors de la présentation du questionnaire au premier temps de mesure.

### Open Science et Politique de transparence

Les données anonymes et la préparation des publications sont mises à disposition sur la plateforme [osf.io](https://osf.io/).

### Protection des données

Les données transmises à l'équipe de recherche ont été anonymisées à la source. Ceci signifie que l'équipe de recherche n'a jamais l'identité des enfants qui ont complété les données.

Malgré cette précaution, les parents et enfants qui le décident peuvent demander suppression de leurs données à tout moment, jusqu'à soumission de l'article.

## Récolte des données

### Modalités

Les données sont récoltées par les enseignantes via papier.

Les données sont anonymisées par les enseignantes (attribution d'un identifiant unique par élève).

### Périodes de récolte des données

Avant intervention : 45 min à un moment parmi les *7-10-11-12 octobre 2022*

Après intervention : 45 min à un moment parmi les *19-20-21-22 décembre 2022*

### Variables mesurées et forme

Chez les élèves : 

- Utilisation des forces (échelle autorapportée)
- Orientation reconnaissante (échelle autorapportée)
- Description de soi (rédaction)
- Qualité des relations dans la classe (sociogramme)

Chez les enseignantes qui dispensent le programme :

- satisfaction professionnelle ((échelle autorapportée))
- Utilisation des forces (échelle autorapportée)

## Documents à disposition au téléchargement

- [Formule de consentement (pour les parents et élèves)](https://www.dropbox.com/s/dj7jn03v75cutpt/20221004-consentement-parent-enfant.pdf?dl=0)
- [Dossier de récolte de mesures (profs)](https://www.dropbox.com/s/mbpjwbhbwgdod2t/20221004-mesures-profs-dossier.pdf?dl=0)
- [Dossier de récolte de mesures (élèves)](https://www.dropbox.com/s/bf5l7uhqs2w3mla/20221004-mesures-enfants-dossier.pdf?dl=0)